{
    "session": {
        "sleep_time": 0,
        "restart_sleep_time": 0,
        "timeout": 0,
        "skip": 0
    },
    "target": {
        "transport": {
            "media": "file",
            "protocol": "file"
        },
        "endpoint": {
            "path": "/mnt/mpeg4/", 
            "filename": "test", 
            "extension": "mp4"
        },
        "conditions": {
            "fail_connection": ["log", "restart"],
            "fail_receive": [],
            "fail_send": ["log"]
        }
    },
    "request": {
        "request_file": "file_MPEG4",
        "graph": 
        [
            {"current": "MPEG4"}
        ]
    }
}
