{
    "session": {
        "sleep_time": 0.1,
        "restart_sleep_time": 0.1,
        "timeout": 0.5,
        "skip": 0
    },
    "target": {
        "transport": {
            "media": "network",
            "protocol": "tcp"
        },
        "endpoint": {
            "address": "10.0.0.11", 
            "port": 9999
        },
        "conditions": {
            "fail_connection": ["log", "restart"],
            "fail_receive": [],
            "fail_send": ["log"]
        }
    },
    "request": {
        "request_file": "network_http",
        "graph": 
        [
            {"current": "GET"}
        ]
    }
}
